/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF,

} from '@react-three/drei'
import {Html} from "@react-three/drei";


export default function Laptop(props) {
  const group = useRef()
  const laptop = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/macbook/model.gltf')
  return (
    <>
      <primitive {...props} object={laptop.scene}>

        <Html
          transform
          wrapperClass="htmlScreen"
          distanceFactor={1.17}
          position={ [ 0, 1.56, - 1.4 ] }
          rotation-x={ - 0.256 }
        >
          <iframe src="https://bruno-simon.com/html/" />
        </Html>

      </primitive>
    </>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/macbook/model.gltf')